#!/bin/bash

set -e


if [ "$1" = "remove" ] ; then
	
	PKG="llx-guest"
	ORIGINAL_FILE_BROWSED="/usr/share/sddm/scripts/Xsetup"
	NEW_DIVERTED_FILE_BROWSED="/usr/share/sddm/scripts/Xsetup.diverted"
	

	if [ -f "$NEW_DIVERTED_FILE_BROWSED" ]; then
		rm -rf "$ORIGINAL_FILE_BROWSED" || true
		dpkg-divert --remove --package ${PKG} --rename --divert "$NEW_DIVERTED_FILE_BROWSED" "$ORIGINAL_FILE_BROWSED"

	fi


fi
#DEBHELPER#

exit 0
