#!/usr/bin/python3

from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QUrl
from PySide6.QtGui import QIcon
from PySide6.QtQml import QQmlApplicationEngine

import sys
import os
import shutil
import pwd
import grp
import gettext
gettext.textdomain("llx-guest-gui")
_ = gettext.gettext

if "PKEXEC_UID" in os.environ:
	currentUser=pwd.getpwuid(int(os.environ["PKEXEC_UID"])).pw_name
else:
	currentUser=os.environ["USER"]

gid = pwd.getpwnam(currentUser).pw_gid
groups_gids = os.getgrouplist(currentUser, gid)
groups = [ grp.getgrgid(x).gr_name for x in groups_gids ]

if "sudo" not in groups and "admins" not in groups and "teachers" not in groups:
	print("  [LlxGuestGui]: No administration privileges")
	msg=_("You need administration privileges to run this application.")
	cmd="kdialog --title 'Llx-Guest' --icon 'llx-guest.svg' --sorry '%s'"%(msg)
	os.system(cmd)
	sys.exit(1)


import LlxGuest
app = QApplication()
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
llxGuestBridge=LlxGuest.LlxGuest()
context.setContextProperty("llxGuestBridge", llxGuestBridge)

url = QUrl("/usr/share/llx-guest/rsrc/llx-guest.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/llx-guest.svg"));
ret=app.exec()
del engine
del app
sys.exit(ret)

