#!/usr/bin/env python3 


import os
import shutil

CHROMIUM_SNAP="/snap/chromium/current/usr/lib/chromium-browser/chrome"

if os.path.exists(CHROMIUM_SNAP):
	
	script='\
#!/bin/bash\n\
\n\
/snap/chromium/current/usr/lib/chromium-browser/chrome --user-data-dir=$HOME --class="ChrUnsnapped" %U\n\
'
	bin_path=os.environ["HOME"]+"/.local/bin/"
	bin_file=bin_path+"chromium"
	if not os.path.exists(bin_path):
		os.makedirs(bin_path)
	
	f=open(bin_file,"w")
	f.write(script)
	f.close()
	os.system("chmod +x %s"%bin_file)
	
	if os.path.exists("/usr/bin/chromium-browser"):
		f=open("/usr/bin/chromium-browser")
		lines=f.readlines()
		f.close()
		
		f=open(bin_file+"-browser","w")
		for line in lines:
			if "exec /snap" in line:
				line=line.replace("/snap/bin/chromium",bin_file)
			f.write(line)
		f.close()
		os.system("chmod +x %s"%(bin_file+"-browser"))
		
	desktop_file="/var/lib/snapd/desktop/applications/chromium_chromium.desktop"
	if os.path.exists(desktop_file):
		f=open(desktop_file)
		lines=f.readlines()
		f.close()
		
		desktop_path=os.environ["HOME"]+"/.local/share/applications/"
		if not os.path.exists(desktop_path):
			os.makedirs(desktop_path)
			
		f=open(desktop_path+"chromium_chromium.desktop","w")
		for line in lines:
			if "Exec=env" in line:
				line=line.replace("/snap/bin/chromium",bin_file)
			f.write(line)
			
		f.close()
		
	
		
	
	

